name: Clean Code

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  codecov:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
          file: ./coverage.xml # optional
          files: ./coverage1.xml,./coverage2.xml # optional
          flags: unittests # optional
          name: codecov-umbrella # optional
          fail_ci_if_error: true # optional (default = false)

  eslint:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 9.8.0
      - name: Install
        run: npm ci
      - name: Run ESLint on changed files
        uses: tj-actions/eslint-changed-files@v4
        with:
          config-path: '.eslintrc'
          ignore-path: '.eslintignore'
          extensions: 'ts,tsx,js,jsx'
          extra-args: '--max-warnings=0'
